/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Before;

import com.jayway.restassured.RestAssured;
import com.jayway.restassured.filter.log.ErrorLoggingFilter;
import com.jayway.restassured.filter.log.ResponseLoggingFilter;
import com.jayway.restassured.response.Header;
import com.jayway.restassured.response.Response;

public class UserTest {
	String authHeader;
	String contentHeader = "application/json";
	@Before
	public void setup() {
		//get aut0token
		Curl
		
		
		RestAssured.baseURI = "https://qa.fitpay.com";
		
	}
	
    @Test public void getUsers() {
    	String URL = null;
    	String Body = "this";
    			Response response = RestAssured
    					.given()
    					.header(authHeader)
    					.header(contentHeader)
    					.when()
    					.get(URL)
    					.then()
    					.statusCode(200)
    					.extract()
    					.response();

    	
    }
}
