/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Before;

import java.util.UUID;
import javax.json.Json;
import com.jayway.restassured.RestAssured;
import com.jayway.restassured.filter.log.ResponseLoggingFilter;
import com.jayway.restassured.response.Header;
import com.jayway.restassured.response.Response;

import org.json.simple.parser.JSONParser;

public class UserTest {
	JSONParser jsonParser = new JSONParser();
	Header authHeader;
	Header contentHeader = new Header("Content-Type","application/json; charset=utf-8");
	@Before
	public void setup() {
		//get aut0token
		authHeader = new Header("Authorization", Auth0Login.getAuthToken());

		
		//For the sake of reading the URL is stored here would put in properties file
		RestAssured.baseURI = "https://api.qa.fitpay.ninja";
		
	}
	
    @Test public void get_10_Users() {
    	
    	/*
    	 * A basic test to endpoint https://qa.fitpay.com/users which returns a list
    	 * of all users on the site
    	 */

    			Response response = RestAssured
    					.given()
	    					.header(authHeader)
	    					.header(contentHeader)
	    				.when()
    						.get("/users?limit=10")
	    				.then()
	    					.statusCode(200)
	    					.extract()
	    					.response();
    			
    		String[] users = response.path("results");
    		
    	assertEquals("the number of users returned is 10", 10, users.length);
    	
    }
    
    @Test public void create_a_User() {
    	
    	/*
    	 * A basic test to post endpoint https://qa.fitpay.com/users 
    	 * to create a user
    	 */
    	String newUserId = UUID.randomUUID().toString();
    	String jsonString = Json.createObjectBuilder()
                .add("id", newUserId)
                .add("createdTs", "2017-07-26T22:51:10.574Z")
                .add("createdTsEpoch","1501109470574")
                .toString();
    	
    	
    	
    			Response response = RestAssured
    					.given()
	    					.header(authHeader)
	    					.header(contentHeader)
	    					.body(jsonString)
	    				.when()
    						.post("/users")
	    				.then()
	    					.statusCode(200)
	    					.extract()
	    					.response();
    			
    		String usersId = response.path("results.id");
    		String message = response.path("message");
    		
        assertEquals("the user was  created", "created new user", message);
    	assertEquals("the userId matches the one we sent", newUserId, usersId);
    	
    }
    
    @Test public void create_a_User_missing_body() {
    	
    	/*
    	 * A basic test to post endpoint https://qa.fitpay.com/users 
    	 * to create a user without a body
    	 */
   	
    			Response response = RestAssured
    					.given()
	    					.header(authHeader)
	    					.header(contentHeader)
	    					.filter(ResponseLoggingFilter.logResponseIfStatusCodeIs(200))
	    				.when()
    						.post("/users")
	    				.then()
	    					.statusCode(400)
	    					.extract()
	    					.response();
    			
    		String message = response.path("message");
    		
    	assertEquals("the user was not able to be created", "Bad Request error", message);
    	
    }
}
